namespace BackendMastery.CoreAPI.CRUDBasics.Database.Models;

/// <summary>
/// Represents a product within the core domain of the application.
/// </summary>
/// <remarks>
/// <para>
/// This class is a <b>domain entity</b> and models how product data exists
/// internally within the system.
/// </para>
/// <para>
/// It is intentionally free from any API, persistence, or UI-specific concerns
/// such as DTOs, database annotations, or serialization attributes.
/// </para>
/// <para>
/// Domain entities encapsulate business data and are typically used by
/// application services and repositories.
/// </para>
/// </remarks>
public class Product
{
    /// <summary>
    /// Gets or sets the unique identifier for the product.
    /// </summary>
    /// <remarks>
    /// This value uniquely identifies a product within the system.
    /// It is typically generated by the application when a new product
    /// is created.
    /// </remarks>
    public Guid Id { get; set; }

    /// <summary>
    /// Gets or sets the display name of the product.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This property is required and should always contain a valid,
    /// non-empty string.
    /// </para>
    /// <para>
    /// A default empty string is assigned to prevent null reference issues
    /// and to align with nullable reference type best practices.
    /// </para>
    /// </remarks>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the monetary price of the product.
    /// </summary>
    /// <remarks>
    /// The price represents the cost of a single unit of the product.
    /// It is expressed as a decimal to avoid floating-point precision issues.
    /// </remarks>
    public decimal Price { get; set; }

    /// <summary>
    /// Gets or sets the date and time when the product was created.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This value typically represents the system timestamp at the moment
    /// the product entity was instantiated or persisted.
    /// </para>
    /// <para>
    /// The time is usually stored in UTC to ensure consistency across
    /// different time zones.
    /// </para>
    /// </remarks>
    public DateTime CreatedAt { get; set; }
}