@BackendMastery.ProdReadiness.EnvironmentConfiguration_HostAddress = http://localhost:5002

GET {{BackendMastery.ProdReadiness.EnvironmentConfiguration_HostAddress}}/weatherforecast/
Accept: application/json

###
