@BackendMastery.ProdReadiness.GracefulDegradation_HostAddress = http://localhost:5130

GET {{BackendMastery.ProdReadiness.GracefulDegradation_HostAddress}}/api/checkout/
Accept: application/json

###
